version: "3"
services:
  vue-front:
    build:
      context: ./front
      dockerfile: Dockerfile
    volumes:
      - ./front:/app
      - /app/node_modules
    working_dir: /app
    ports:
      - 3000:3000
